<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
	  <RepoPath>F:\vsrepos\CustomizeLib.BepInEx</RepoPath>
	  <PluginsPath>F:\PVZRH_Bep\BepInEx\plugins</PluginsPath>
	  <InnerPath>F:\PVZRH_Inner\BepInEx\plugins</InnerPath>
	  <ResPath>$(RepoPath)\Res</ResPath>
	  <LangVersion>preview</LangVersion>
	  <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	  <EnablePreviewFeatures>true</EnablePreviewFeatures>
  </PropertyGroup>
  <ItemGroup>
    <Reference Remove="@(Reference)" />
    <Reference Include="$(RepoPath)\GameLib\*.dll">
      <Private>false</Private>
    </Reference>
  </ItemGroup>
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
  <Exec Command="COPY &quot;$(TargetPath)&quot; &quot;$(ResPath)&quot;" />
  <Exec Command="COPY &quot;$(TargetPath)&quot; &quot;$(PluginsPath)&quot;" />
</Target>
	<PropertyGroup>
		<NoWarn>$(NoWarn);MSB3277</NoWarn>
	</PropertyGroup>
</Project>

























































